name: Artikel
favicon: null
layout_spectrum: 0.26143
typography_spectrum: 0.49037
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0072a9'
    - '#fefefe'
    - '#6197b9'
    - '#000000'
    - '#e9b838'
  brandStrength: 0
  lightness: 0.75
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
